version: '3.8'

services:
  celery-worker:
    container_name: celery-worker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src
